### ISSUE TITLE
Random TODO

### ISSUE THREAD

**Issue by dman7** [socialappslab/denguetorpedo#286]
I'm adding this quickly to keep this in a centralized place:
- Replace the address with neighborhood
  - [x] Spanish: Nombre el barrio donde encontró el foco
- Add a popup on the Google Maps div.
  - [ ] Spanish: Muéveme donde encontraste el foco
- Add below the address text that says “Move the marker to the exact location”
  - [ ] Spanish: Haga click y mueva el marcador donde encontró el foco
- [x] Make envelope bigger
- [x] Make the envelope to send to teams, communities, and individuals.
