### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dman7** [socialappslab/denguetorpedo#583]
- [ ] Report with photo does not appear in Criaderos feed.
- [ ] Add a column that says “photo/no photo” on cvs_reports#index
- [ ] Add warning message before deleting reports.
- [ ] Add warning message before deleting CSV_reports
- [ ] Remove CSV from Dashboard
- [ ] Allow for “no photos” but push for uploading with photo (Make it jump out)
- [ ] There are many labels associated with a single report: https://www.denguechat.org/neighborhoods/5/reports
- [ ] When users upload same CSV with an already existing report, we want to ensure that a new report is NOT created. We want to update the existing report.
- [ ] Add updates from other neighborhoods (whether a small window, or as part of feed). Suggestion from Harold: Not much interaction bw neighborhoods. Add blog posts within the feed.
- [ ] Aggregate statistics for a neighborhood (Francisco Meza total visits, percent were positive, percent were potential) —> Show it in a graph.
- [ ] Add toggle for locations/visits when graphic data (currently: we’re displaying percentages of locations).
- [ ] Change parsing... —> Working… (Procesando…)
- [ ] Remove "Barrel summary", and add barrel summary by visit (after total positive/potencial)
  - [ ] Remove larvae/pupae, and add total barrels, total barrels positive, total barrels potential, total barrels abatizado (barriles table: total, positivos , potenciales, abatizados)
