### ISSUE TITLE
Website TODO

### ISSUE THREAD

**Issue by dman7** [socialappslab/denguetorpedo#725]
- [x] Dropdown menu to select a specific community from navigation bar
- [x] Dropdown menu to select a specific city from navigation bar
- [x] Lugares con -> Casas con
- [x] In Community View: to be able to toggle each of the risks (red, green, yellow)
- [x] Add table below the graph (hide it by default and be able to show it) --> the table is the one that appears when you toggle over the graph 
- [x] Lugares -> Casas in table
- [x] The accounts and roles
  - [x] Regular user
  - [x] Facilitator
  - [x] Admin

### Organization context
- [x] Organization: SSI
  - [x] All users associated with SSI

### CityBlock model
  - [x] a bunch of locations associated with it
  - [x] Name of block
  - [x] Associated city
  - [x] Associated neighborhood

## District model
- [x] Belongs to a city
- [x] Has many neighborhoods
- [x] Districto 3 needs to change to District, and be part of Managua the city
