### ISSUE TITLE
Random TODO

### ISSUE THREAD

**Issue by dman7** [socialappslab/denguetorpedo#739]
- [ ] Images scale down/up and are not scaled appropriately. Make sure that they scale appropriately.
- [ ] Ability to edit a comment
- [x] Add secondary navigation bar for Datos: add Datos to main navigation bar
- [x] ~~Facilitators wants to see all incoming data (from mobile phone and CSV)~~ Replaced by https://github.com/socialappslab/denguetorpedo/issues/767
- [ ] Info icon for hover ability next to the neighborhood name
