### ISSUE TITLE
Restore production Redis database

### ISSUE THREAD

**Issue by dman7** [socialappslab/denguetorpedo#835]
I've successfully retrieved a backup of Redis database that was hosted on Heroku. This database is available through Dmitri's Dropbox link:

https://drive.google.com/open?id=16Ti3b8IOcXZ0b7NsenGZsHo5eAXNWhTC

In order to successfully restore this database, we need to

- [ ] Fix various Docker issue (see associated issue)
- [ ] Add terminal access (optional)
- [ ] Run the restore command (see the article below)
- [ ] Fix various bugs that may occur after restore command

I will be following instructions from this article: https://www.digitalocean.com/community/tutorials/how-to-back-up-and-restore-your-redis-data-on-ubuntu-14-04

```
redis-cli -a r3d1s_prod && /bitnami/redis/data
scp dmitriskj@scp.couchdrop.io:/Dropbox/2018-06-15T20_45_45.rdb /opt/bitnami/redis/data/dump.rdb && chown redis:redis dump.rdb && chmod 660 dump.rdb
```
