### ISSUE TITLE
Review current points model and make a checklist of changes

### ISSUE THREAD

**Issue by cdparra** [socialappslab/denguetorpedo#874]
Review current points model and make a checklist of what's needed for this to work with the new assignments model that records who is actually visiting the houses

Current puntuation system is here: https://github.com/socialappslab/denguetorpedo/blob/master/app/models/user.rb#L29

Accoding to this:
```ruby
  # A user gets points for the following:
  # * verifying a report,
  # * submitting a report (via SMS or web),
  # * eliminating a report.
  module Points
    REPORT_VERIFIED  = 50
    REPORT_SUBMITTED = 50
    POST_CREATED     = 5
    REFERRAL         = 50
    GREEN_HOUSE      = 200

    # Points for certain badges
    WATCHER      = 50
    EXTERMINATOR = 225
    WARRIOR      = 450
    HEALTHWORKER = 675
    PROTECTOR    = 900
  end
```

It is not clear who is awarded every green house's points. Apparently, they are awarded to the person that uploads a CSV with inspections (which is the user associated with the inspection). Considering the use of the ODK Sync Worker, and the new assignments model, we need to: 

- [x] Identify where exactly are the points awarded
- [x] Check that they are being awarded correctly now that the `reports` model has been deprecated in favor of the inspection model 
- [x] Use the information from the `assignments` table to decide who are the `reporters` of an inspection: i.e., if an inspection from date `d1` is associated with house `12345678`, then all the users who were assigned the city block where this house is located (e.g., `12345`) should be considered as `reporters` of the breeding site, and therefore get the points associated with this. Same logic applies to awarding points for green houses. 
- [x] Create a list of issues to address so that points start to be awarded in such a way that it considers the assignments model.
